import * as XLSX from 'xlsx'

export const PRODUCTS_HEADERS = [
  'name',
  'slug',
  'design_number',
  'category_code',
  'collection_slug',
  'product_number',
  'base_metal',
  'status',
  'making_charge_pct',
  'short_desc',
  'description',
  'is_featured',
  'is_new_arrival',
  'is_best_seller',
  'is_coming_soon',
  'meta_title',
  'meta_description',
  'diamond_shape',
  'diamond_count',
  'total_diamond_wt',
  'diamond_color',
  'diamond_clarity',
  'size_range',
  'has_stone',
  'stone_lines_json',
  'stone_1_name',
  'stone_1_cut_size',
  'stone_1_shape',
  'stone_1_color',
  'stone_1_count',
  'stone_1_rate_inr',
  'color_code',
  'color_images',
  'color_videos',
  'purity_code',
  'metal_weight_g',
  'stock_qty',
  'variant_active',
] as const

const EXAMPLE_ROWS = [
  {
    name: 'Halo Solitaire Ring',
    slug: '',
    design_number: 'AMI-1001',
    category_code: 'RN',
    collection_slug: '',
    product_number: '',
    base_metal: 'gold',
    status: 'draft',
    making_charge_pct: 8,
    short_desc: 'Elegant halo ring',
    description: '',
    is_featured: 'N',
    is_new_arrival: 'N',
    is_best_seller: 'N',
    is_coming_soon: 'N',
    meta_title: '',
    meta_description: '',
    diamond_shape: 'Round',
    diamond_count: 12,
    total_diamond_wt: 0.45,
    diamond_color: 'EF',
    diamond_clarity: 'VVS',
    size_range: '12-18',
    has_stone: 'N',
    stone_lines_json: '',
    stone_1_name: '',
    stone_1_cut_size: '',
    stone_1_shape: '',
    stone_1_color: '',
    stone_1_count: '',
    stone_1_rate_inr: '',
    color_code: 'YG',
    color_images: '',
    color_videos: '',
    purity_code: '18',
    metal_weight_g: 4.2,
    stock_qty: 3,
    variant_active: 'Y',
  },
  {
    name: 'Halo Solitaire Ring',
    slug: '',
    design_number: 'AMI-1001',
    category_code: 'RN',
    collection_slug: '',
    product_number: '',
    base_metal: 'gold',
    status: 'draft',
    making_charge_pct: 8,
    short_desc: 'Elegant halo ring',
    description: '',
    is_featured: 'N',
    is_new_arrival: 'N',
    is_best_seller: 'N',
    is_coming_soon: 'N',
    meta_title: '',
    meta_description: '',
    diamond_shape: 'Round',
    diamond_count: 12,
    total_diamond_wt: 0.45,
    diamond_color: 'EF',
    diamond_clarity: 'VVS',
    size_range: '12-18',
    has_stone: 'N',
    stone_lines_json: '',
    stone_1_name: '',
    stone_1_cut_size: '',
    stone_1_shape: '',
    stone_1_color: '',
    stone_1_count: '',
    stone_1_rate_inr: '',
    color_code: 'WG',
    color_images: '',
    color_videos: '',
    purity_code: '14',
    metal_weight_g: 3.9,
    stock_qty: 2,
    variant_active: 'Y',
  },
]

const MINIMAL_EXAMPLE_ROW = {
  name: 'Minimal Import Example',
  slug: 'minimal-import-example',
  design_number: 'AMI-MIN-01',
  category_code: '',
  collection_slug: '',
  product_number: '',
  base_metal: '',
  status: '',
  making_charge_pct: '',
  short_desc: '',
  description: '',
  is_featured: '',
  is_new_arrival: '',
  is_best_seller: '',
  is_coming_soon: '',
  meta_title: '',
  meta_description: '',
  diamond_shape: '',
  diamond_count: '',
  total_diamond_wt: '',
  diamond_color: '',
  diamond_clarity: '',
  size_range: '',
  has_stone: '',
  stone_lines_json: '',
  stone_1_name: '',
  stone_1_cut_size: '',
  stone_1_shape: '',
  stone_1_color: '',
  stone_1_count: '',
  stone_1_rate_inr: '',
  color_code: '',
  color_images: '',
  color_videos: '',
  purity_code: '',
  metal_weight_g: 3.5,
  stock_qty: '',
  variant_active: '',
}

const REFERENCE_ROWS = [
  { type: 'required', code: 'name', label: 'Product name — REQUIRED' },
  { type: 'required', code: 'design_number or slug', label: 'Design number or slug — REQUIRED (slug used if design_number blank)' },
  { type: 'required', code: 'metal_weight_g', label: 'Net metal weight in grams — REQUIRED per variant row' },
  { type: 'note', code: 'lenient', label: 'Extra columns ignored. Missing optional fields use defaults (category, colour, purity, stock 0, draft status).' },
  { type: 'note', code: 'edit', label: 'Open each product in CMS to add images, description, and publish.' },
  { type: 'category_code', code: 'BR', label: 'Bracelet' },
  { type: 'category_code', code: 'RN', label: 'Ring' },
  { type: 'category_code', code: 'ER', label: 'Earring' },
  { type: 'category_code', code: 'NK', label: 'Necklace' },
  { type: 'category_code', code: 'BG', label: 'Bangle' },
  { type: 'category_code', code: 'PD', label: 'Pendent' },
  { type: 'category_code', code: 'CN', label: 'Chain' },
  { type: 'category_code', code: 'PL', label: 'Payel' },
  { type: 'category_code', code: 'MS', label: 'Mangal Sutra' },
  { type: 'category_code', code: 'NP', label: 'NosePin' },
  { type: 'color_code', code: 'YG', label: 'Yellow Gold' },
  { type: 'color_code', code: 'WG', label: 'White Gold' },
  { type: 'color_code', code: 'RG', label: 'Rose Gold' },
  { type: 'color_code', code: 'SV', label: 'Sterling Silver' },
  { type: 'purity_code', code: '18', label: '18Kt Gold (gold products)' },
  { type: 'purity_code', code: '14', label: '14Kt Gold (gold products)' },
  { type: 'purity_code', code: '09', label: '9Kt Gold (gold products)' },
  { type: 'purity_code', code: '925', label: '925 Silver (silver products)' },
  { type: 'purity_code', code: '835', label: '835 Silver (silver products)' },
  { type: 'base_metal', code: 'gold', label: 'Gold jewellery' },
  { type: 'base_metal', code: 'silver', label: 'Silver jewellery' },
  { type: 'status', code: 'draft', label: 'Draft (images can be added later)' },
  { type: 'status', code: 'active', label: 'Published (requires images per colour)' },
  { type: 'flag', code: 'Y / N', label: 'is_featured, is_new_arrival, variant_active, etc.' },
  { type: 'media', code: 'url1|url2', label: 'Pipe-separated Cloudinary URLs in color_images / color_videos' },
]

export function buildBulkImportWorkbook(): Buffer {
  const wb = XLSX.utils.book_new()

  const productsSheet = XLSX.utils.json_to_sheet([...EXAMPLE_ROWS, MINIMAL_EXAMPLE_ROW], { header: [...PRODUCTS_HEADERS] })
  XLSX.utils.book_append_sheet(wb, productsSheet, 'Products')

  const refSheet = XLSX.utils.json_to_sheet(REFERENCE_ROWS)
  XLSX.utils.book_append_sheet(wb, refSheet, 'Reference')

  const out = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer
  return out
}
